Progress Update 3

-----
- **Recap:**
  - Finn presented an introduction to Maui and we spent time planning out the structure of our application more.
  - Researched more applications of WHT and started addressing the marketability issues.
  - Started the Maui project
  - Researched graphing API plotly
  - Started matrix generating algorithm
- **Tasks completed**
  - Description of tasks completed (and by whom)
    - General**:** All members continued to find resources and conduct research regarding the technologies/math needed to create this application.
    - Derik: Research applications of final MVP. Some work on the matrix generator.
    - Kain: Research WHT and Fourier transforms in general
    - Chet: C# experimentation, Familiarize with Maui Blazor
    - Calvin: Researched WHT more, looked into Maui Blazor, and experimented with some C#.
    - Finn: Gave a presentation on Maui Blazor. Started working on initial app set up.
- **Successes**
  - Accomplishments:
    - Got everyone up to speed on Maui Blazor.
    - Started moving the project in a more marketable direction.
    - Learned more about the graphing API.
  - Lessons:
    - We need to think more about why we are doing this project.
- **Roadblocks/challenges**
  - Challenges overcome:
    - Everyone now has a more fundamental understanding of how to use Maui Blazor.
  - Challenges remaining:
    - Expanding the marketability of the project.
    - We are at a point where we will need to start programming to continue our roadmap.
    - Need to solidify a timeline.
  - Help Needed:
    - Possible ideas on expanding the marketability of the project
- **Changes/Deviations**
  - Likely all code will be in c# now.
  - Will focus on JSON output first, then .csv
- **Confidence** on completion of the project for each team member and the group average
  - Derik: 5 , I think we are at a good point to start work. We can learn much more about our trajectory and how reasonable our plan is once we take a few steps. 
  - Finn: 5, no change from last time. I still think the project is very doable..
  - Calvin: 5, I believe that we will complete the initial goals of our project in a good amount of time. Each person has a solid task with room to help others as well. 
  - Kain: 5, I understand my portion pretty well, whether or not i can program it is in question but we have a lot of time to debug it. 
  - Chet: 5, It is realistic to think that we will complete the initial project in the time given to us
- **Group dynamics**
  - Derik: Everyone is working well and seems invested in our success. Everyone is eager to get started.
  - Finn: The group is still working well together, no issues. .
  - Calvin: Everyone is still very involved and excited about the project, so I think everyone will be able to work really well together and build a cool product.
  - Kain: We all work together well so far and basically know our jobs already.
  - Chet: It's looking like everyone is enjoying the group so far, and there has been nothing we haven’t been able to figure out..

